insert into CUSTOMER_ORDER (ORDER_ID, CUSTOMER_NAME,ORDER_DATE,SHIPPING_ADDRESS,TOTAL,ORDER_ITEM_ID)values (100,'Alok',sysdate(),'12221 PLAZA DR PARMA 44130',345,200);
insert into CUSTOMER_ORDER (ORDER_ID, CUSTOMER_NAME,ORDER_DATE,SHIPPING_ADDRESS,TOTAL,ORDER_ITEM_ID)values (101,'Yuvraj',sysdate(),'20000 LORAIN CLEVELAND OH 44126',200,201);
insert into CUSTOMER_ORDER (ORDER_ID, CUSTOMER_NAME,ORDER_DATE,SHIPPING_ADDRESS,TOTAL,ORDER_ITEM_ID)values (102,'Ajinkya',sysdate(),'34/D23 Village park, Magarpatta, Pune',230,203);

